name: Org File Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  org_file_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/org-file-sync@9db43e72dd8c2d92a919c2ae895f33a54e626aa4
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          repos: |
            dev-infra
          files: |
            CODE_OF_CONDUCT.md
            SECURITY.md
