name: Org File Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  org_file_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/org-file-sync@3c526cbb36b8517829dbbf02a7833fa3081479bb
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          repos: |
            angular
            angular-cli
            components
            code-of-conduct
            dev-infra
            universal
            vscode-ng-language-service
          files: |
            CODE_OF_CONDUCT.md
            SECURITY.md
